version: '2'
services:
    cardiotool-app:
        image: cardiotool
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cardiotool-mysql:3306/cardiotool?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cardiotool-elasticsearch:9300
        ports:
            - 8080:8080
    cardiotool-mysql:
        extends:
            file: mysql.yml
            service: cardiotool-mysql
    cardiotool-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cardiotool-elasticsearch
